### PR TITLE
Added extra tokens for contributions. 

### PR DESCRIPTION
**Pull request by jaapjansma**
This was needed for a client of us.

### CODE REVIEW

**Comment by jaapjansma** [comment]
This PR fixes issue #15, #16, and #17 and #19

**Comment by jaapjansma** [comment]
@eileenmcnaughton could you merge this pr and create a new version of the extension?

**Comment by eileenmcnaughton** [comment]
Hi @jaapjansma these seem like useful tokens & yes I will merge & cut a release.

I would note that I'm starting to push this extension to the next level & adding unit tests. I'm not going to insist on tests this time but I may do for future submissions

**Comment by jaapjansma** [comment]
@eileenmcnaughton thanks. I am not sure how to test whether a token works so if you have an example of a unit tests I can provide some this week.

**Comment by eileenmcnaughton** [comment]
@jaapjansma I think you could do something like create a token & then call Contribution.sendconfirmation api - or possibly Message.SendTemplate - but also you might be able to call the function more directly.

Note that to add a hook you need to do something like https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/api/v3/ACLPermissionTest.php#L79

**Comment by jaapjansma** [comment]
ehm the example given is just testing whether the hook worsk. However I want to test whether the hook in my extension gets called and whether the tokens are processed into correct data. I am not sure how to accamplish that.

**Comment by eileenmcnaughton** [comment]
the extension sets up how get your hook to be called - although I guess in extensions that is 'already done' since they are enabled.  [This test ](https://github.com/aydun/civicrm-core/blob/6298b166bb533b33e511da6ca4e437475f9d47c4/tests/phpunit/api/v3/ContributionTest.php#L1753)
a) changes the message_template text & 
b) checks the message output 
so it might be closer to filling the gaps?

**Comment by eileenmcnaughton** [comment]
See https://github.com/eileenmcnaughton/nz.co.fuzion.civitoken/pull/46 for fix for regression caused by this

**Pull request merged**
