### PR TITLE
Added relationship tokens for b to a

### PR DESCRIPTION
**Pull request by jaapjansma**
This PR adds tokens for relations from b to a.
So for example if you want to sent a letter to a household you can now use a token for the first name of the head of the household.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jaapjansma well it passes & it's a test so those are both good things :-)

**Comment by MegaphoneJon** [comment]
I'm in favor of this, but wanted to make sure that @jaapjansma knows about the [reltoken extension](https://civicrm.org/extensions/related-tokens) which IMO gives the best UX around tokens for relationships.

**Comment by jaapjansma** [comment]
haha, nice way for letting me know the existence of reltoken extension.

**Pull request merged**
